name: Publish docker image to ghcr.io

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_UPPERCASE: ${{ github.repository }}
  USERNAME_UPPERCASE: ${{ github.repository_owner }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set the version environment variable and make the environment variables lowercase.
        # Get the version from the tag (e.g. v1.2.3 --> 1.2.3).
        # Also make the environment variables lowercase (https://github.com/orgs/community/discussions/25768#discussioncomment-8057564).
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> ${GITHUB_ENV}
          echo "IMAGE_NAME=${IMAGE_NAME_UPPERCASE}@L" >> ${GITHUB_ENV}
          echo "USERNAME=${USERNAME_UPPERCASE@L}" >> ${GITHUB_ENV}
      - name: Log in to the registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.ACCESS_TOKEN }}
      - name: Build and push the web image.
        run: |
          docker build ./apps/web/ --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.RELEASE_VERSION }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.RELEASE_VERSION }}
