name: Publish docker image to ghcr.io

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  REGISTRY: ghcr.io
  RAW_USERNAME: ${{ github.repository_owner }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set the version environment variable and make the environment variables lowercase.
        env:
          RAW_IMAGE_REPOSITORY: ${{ github.repository }}
        # Get the version from the tag (e.g. v1.2.3 --> 1.2.3).
        # Also make the environment variables lowercase (https://github.com/orgs/community/discussions/25768#discussioncomment-8057564).
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/*/v}
          IMAGE_REPOSITORY_WEBSITE=${RAW_IMAGE_REPOSITORY@L}-website
          echo "USERNAME=${RAW_USERNAME@L}" >> ${GITHUB_ENV}
          echo "FULL_IMAGE_URL_WEBSITE=${REGISTRY}/$IMAGE_REPOSITORY_WEBSITE:$RELEASE_VERSION" >> ${GITHUB_ENV}
      - name: Log in to the registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.RAW_USERNAME }}
          password: ${{ secrets.ACCESS_TOKEN }}
      - name: Build and push the web image.
        run: |
          docker build --file ./apps/web/Dockerfile . --no-cache --tag ${{ env.FULL_IMAGE_URL_WEBSITE }}
          docker push ${{ env.FULL_IMAGE_URL_WEBSITE }}
