name: Publish docker image to ghcr.io

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  USERNAME: ${{ github.repository_owner }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push the web image.
      - uses: actions/checkout@v4
      # Get the version from the tag (e.g. v1.2.3 --> 1.2.3)
      - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      - run: cat ${{ secrets.ACCESS_TOKEN }} | docker login --username ${{ env.USERNAME }} --password-stdin ${{ env.REGISTRY }}
      - run: docker build ./apps/web/ --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.RELEASE_VERSION }}
      - run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.RELEASE_VERSION }}
